import { readFileSync, existsSync } from 'node:fs';
import assert from 'node:assert/strict';

assert.ok(existsSync('index.html'), 'index.html should exist');
assert.ok(existsSync('styles.css'), 'styles.css should exist');
assert.ok(existsSync('script.js'), 'script.js should exist');
assert.ok(existsSync('package.json'), 'package.json should exist');
assert.ok(existsSync('motion.js'), 'premium motion script should exist');
assert.ok(existsSync('image-warp.js'), 'image cursor warp script should exist');
assert.ok(existsSync('variable-proximity.js'), 'safe VariableProximity script should exist');
assert.ok(existsSync('assets/person-hero-user-final.png'), 'person hero asset should exist');
assert.ok(existsSync('assets/tree-roots.jpg'), 'tree roots asset should exist');
assert.ok(existsSync('assets/tree-roots-reveal.png'), 'second roots reveal asset should exist');
assert.ok(existsSync('assets/lanyard-front.jpg'), 'Lanyard front image should be copied into site assets');
assert.ok(existsSync('components/Lanyard.jsx'), 'React Bits Lanyard component should be present');
assert.ok(existsSync('components/Lanyard.css'), 'React Bits Lanyard CSS should be present');
assert.ok(existsSync('components/card.glb'), 'React Bits card.glb should be present');
assert.ok(existsSync('components/lanyard.png'), 'React Bits lanyard.png should be present');
assert.ok(existsSync('lanyard-entry.jsx'), 'homepage Lanyard mount entry should be present');
assert.ok(existsSync('lanyard-entry.bundle.js'), 'homepage Lanyard browser bundle should be present');
assert.ok(existsSync('lanyard-entry.bundle.css'), 'homepage Lanyard browser CSS should be present');

const html = readFileSync('index.html', 'utf8');
const css = readFileSync('styles.css', 'utf8');
const siteScript = readFileSync('script.js', 'utf8');
const motion = readFileSync('motion.js', 'utf8');
const imageWarp = existsSync('image-warp.js') ? readFileSync('image-warp.js', 'utf8') : '';
const rootsReveal = existsSync('roots-reveal.js') ? readFileSync('roots-reveal.js', 'utf8') : '';
const variableProximity = existsSync('variable-proximity.js') ? readFileSync('variable-proximity.js', 'utf8') : '';
const packageJson = JSON.parse(readFileSync('package.json', 'utf8'));

for (const id of ['home', 'roots', 'about', 'skills', 'work', 'contact']) {
  assert.match(html, new RegExp(`id="${id}"`), `section #${id} should exist`);
}

assert.match(html, /自媒体运营经验/, 'profile text should be included');
assert.match(html, /短视频剪辑/, 'short-video editing capability should be included');
assert.match(html, /私域运营/, 'private-domain operations capability should be included');
assert.match(css, /--page-bg:\s*#7a7a7a/, 'unified sampled medium-gray page base should be defined');
assert.doesNotMatch(css, /background:\s*#111/i, 'opening/background panels should use the unified page base');
assert.match(html, /person-hero-user-final\.png/, 'home should use the intact hero image');
assert.match(html, /tree-roots-reveal\.png/, 'roots should use the original reveal image and effect');
assert.match(html, /class="full-media roots-reveal-media"/, 'roots should layer the reveal image without changing the base image');
assert.match(html, /roots-reveal\.js/, 'roots cursor reveal behavior should be loaded');
assert.match(html, /type="module" src="roots-reveal\.js/, 'roots vegetation motion should load as an isolated module');
assert.match(css, /\.roots-reveal-media[\s\S]*radial-gradient/, 'roots reveal should use a circular radial mask');
assert.match(css, /roots-reveal-canvas/, 'roots reveal should support a motion canvas without changing layout');
assert.match(css, /--reveal-x/, 'roots reveal mask should follow a horizontal pointer coordinate');
assert.match(css, /--reveal-y/, 'roots reveal mask should follow a vertical pointer coordinate');
assert.match(rootsReveal, /from 'ogl'/, 'roots vegetation motion should use bundled OGL imports for production');
assert.match(rootsReveal, /vegetationMask/, 'roots motion should isolate green vegetation from the trunk');
assert.match(rootsReveal, /uTime/, 'roots vegetation should use slow continuous shader motion');
assert.match(rootsReveal, /IntersectionObserver/, 'roots motion should pause when the second page is off screen');
assert.match(rootsReveal, /dpr:\s*pixelRatio/, 'roots canvas should use renderer DPR without enlarging its CSS box');
assert.match(rootsReveal, /renderer\.setSize\(width, height\)/, 'roots canvas should keep the same display dimensions as the base image');
assert.doesNotMatch(rootsReveal, /renderer\.setSize\(width \* pixelRatio, height \* pixelRatio\)/, 'roots canvas must not apply DPR twice');
assert.match(rootsReveal, /broadWind \* 0\.0042/, 'vegetation sway should be visible without moving the trunk');
assert.doesNotMatch(css, /scroll-snap-type/, 'page scrolling should not snap to fixed panels');
assert.doesNotMatch(css, /scroll-snap-align/, 'sections should allow free scrolling stops');
assert.ok(packageJson.dependencies?.gsap, 'gsap dependency should be installed');
assert.match(html, /opening-animation/, 'home should include a full opening animation layer');
assert.doesNotMatch(html, /node_modules\/gsap/, 'production HTML must not reference node_modules gsap files directly');
assert.match(motion, /from 'gsap'/, 'motion should import gsap through Vite bundling');
assert.match(motion, /from 'gsap\/ScrollTrigger'/, 'motion should import ScrollTrigger through Vite bundling');
assert.match(html, /motion\.js/, 'premium motion script should be loaded');
assert.match(html, /variable-proximity\.js/, 'safe VariableProximity script should be loaded');
assert.match(css, /clip-path/, 'image reveal should use performant clipping');
assert.match(html, /data-hero-depth/, 'home hero should use layered depth markup');
assert.match(html, /hero-layer-person/, 'hero should include a foreground character layer');
assert.match(html, /hero-layer-shadow/, 'hero should include a background shadow layer');
assert.match(html, /hero-layer-type/, 'hero should include a background typography layer');
assert.match(html, /hero-cursor-glow/, 'hero should include a subtle cursor glow layer');
assert.match(html, /hero-stagger-curtain/, 'home should include a staggered opening curtain after the YI XUAN intro');
assert.match(html, /stagger-slice/, 'staggered opening curtain should use sliced panels');
assert.match(html, /lanyard-toggle/, 'home should include a button to open the Lanyard pendant');
assert.match(html, /lanyard-root/, 'home should include an isolated Lanyard mount target');
assert.match(html, /lanyard-loader\.js/, 'home should load only the lightweight Lanyard loader');
assert.doesNotMatch(html, /src="lanyard-entry\.bundle\.js/, 'heavy Lanyard bundle should not load before the button is clicked');
assert.doesNotMatch(html, /lanyard-entry\.bundle\.css/, 'home should not depend on a prebuilt Lanyard CSS file');
assert.match(css, /lanyard-toggle/, 'Lanyard trigger should be styled without changing the hero layout');
assert.match(css, /lanyard-drop/, 'Lanyard should drop from the top over the existing homepage');
assert.doesNotMatch(css, /\.lanyard-modal[\s\S]*backdrop-filter/, 'Lanyard should not use a full modal backdrop');
assert.ok(packageJson.dependencies?.react, 'react should be installed for the React Bits component');
assert.ok(packageJson.dependencies?.['react-dom'], 'react-dom should be installed for the React Bits component');
assert.ok(packageJson.dependencies?.three, 'three should be installed for Lanyard');
assert.ok(packageJson.dependencies?.meshline, 'meshline should be installed for Lanyard');
assert.ok(packageJson.dependencies?.['@react-three/fiber'], '@react-three/fiber should be installed for Lanyard');
assert.ok(packageJson.dependencies?.['@react-three/drei'], '@react-three/drei should be installed for Lanyard');
assert.ok(packageJson.dependencies?.['@react-three/rapier'], '@react-three/rapier should be installed for Lanyard');
const lanyardEntry = existsSync('lanyard-entry.jsx') ? readFileSync('lanyard-entry.jsx', 'utf8') : '';
const lanyardLoader = existsSync('lanyard-loader.js') ? readFileSync('lanyard-loader.js', 'utf8') : '';
const lanyardComponent = existsSync('components/Lanyard.jsx') ? readFileSync('components/Lanyard.jsx', 'utf8') : '';
assert.match(lanyardEntry, /frontImage="\/assets\/lanyard-front\.jpg"/, 'Lanyard should use the provided JPG as frontImage');
assert.match(lanyardEntry, /imageFit="cover"/, 'Lanyard should use cover to remove white card image margins');
assert.match(lanyardEntry, /cardScale=\{1\.68\}/, 'Lanyard card should be scaled down for the homepage');
assert.match(lanyardEntry, /lanyardWidth=\{0\.82\}/, 'Lanyard band should be slimmer after the card is reduced');
assert.match(lanyardEntry, /export function mountLanyard/, 'Lanyard React island should be mounted only when requested');
assert.match(lanyardEntry, /ReactDOM\.createRoot/, 'Lanyard should mount as a React island');
assert.match(lanyardLoader, /import\('\.\/lanyard-entry\.jsx/, 'Lanyard loader should import the React island source on click');
assert.match(lanyardEntry, /lanyard-drop/, 'Lanyard entry should render a top-drop hanging layer');
assert.match(lanyardEntry, /Escape/, 'Lanyard should close from the keyboard without a modal page');
assert.match(lanyardEntry, /onClick/, 'Lanyard entry should support click interactions');
assert.match(lanyardComponent, /export default function Lanyard/, 'Lanyard should keep the React Bits component shape');
assert.match(lanyardComponent, /frontImage/, 'Lanyard should support frontImage');
assert.match(lanyardComponent, /imageFit/, 'Lanyard should support imageFit');
assert.match(lanyardComponent, /cardScale/, 'Lanyard should support cardScale for homepage sizing');
assert.match(lanyardComponent, /meshPhysicalMaterial[\s\S]*transparent[\s\S]*clearcoat/, 'Lanyard should add a transparent card sleeve');
assert.match(lanyardComponent, /card\.glb/, 'Lanyard should import card.glb');
assert.match(lanyardComponent, /lanyard\.png/, 'Lanyard should import lanyard.png');
assert.match(css, /hero-noise/, 'hero should include a lightweight noise atmosphere layer');
assert.match(css, /hero-stagger-curtain/, 'staggered opening curtain should be styled as a temporary overlay');
assert.ok(packageJson.dependencies?.ogl, 'ogl dependency should stay available for the image warp shader');
assert.match(html, /hero-image-warp-field/, 'home hero should include the image warp canvas field');
assert.match(html, /image-warp\.js/, 'home should load the image warp script');
assert.match(css, /hero-image-warp-field/, 'image warp canvas field should be styled without changing layout');
assert.match(imageWarp, /sampler2D\s+uImage/, 'image warp shader should distort the hero image texture');
assert.match(imageWarp, /uMouse/, 'image warp should follow the cursor');
assert.match(imageWarp, /uRadius/, 'image warp should affect a local cursor region');
assert.match(imageWarp, /uStrength/, 'image warp should expose distortion strength');
assert.match(imageWarp, /startRenderLoop/, 'image warp should only render while pointer distortion is active');
assert.match(imageWarp, /0\.14/, 'image warp should use a tighter cursor distortion radius');
assert.match(imageWarp, /0\.065/, 'image warp should use a stronger visible distortion strength');
assert.match(imageWarp, /color\.a\s*\*=\s*edge\s*\*\s*influence/, 'image warp should be the earlier local overlay distortion version');
assert.match(imageWarp, /sin\(\(dist \* 0\.075\) - \(uTime \* 5\.5\)\)/, 'image warp should restore the earlier no-star ripple distortion');
assert.doesNotMatch(imageWarp, /waterRipple|uFlowSpeed/, 'image warp should be returned to the no-star non-water version');
assert.doesNotMatch(imageWarp, /is-warp-ready/, 'image warp should not hide the original hero image layers');
assert.match(imageWarp, /from 'ogl'/, 'image warp should use bundled OGL imports for production');
assert.match(imageWarp, /new Renderer/, 'image warp should use the OGL renderer');
assert.doesNotMatch(imageWarp, /StarLayer|uMouseRepulsion|NUM_LAYER/, 'image warp should not render Galaxy stars');
assert.match(css, /variable-proximity-active/, 'safe VariableProximity should have scoped active styling');
assert.match(variableProximity, /fromFontVariationSettings/, 'safe VariableProximity should keep the React Bits setting names');
assert.match(variableProximity, /toFontVariationSettings/, 'safe VariableProximity should keep the React Bits setting names');
assert.match(variableProximity, /calculateFalloff/, 'safe VariableProximity should calculate cursor falloff');
assert.match(variableProximity, /radius\s*=\s*120/, 'safe VariableProximity should use a proximity radius for text');
assert.match(variableProximity, /querySelectorAll/, 'safe VariableProximity should target existing text elements');
assert.doesNotMatch(variableProximity, /TreeWalker|replaceWith|createTextNode|variable-proximity-letter/, 'safe VariableProximity must not split text into letters');
assert.match(css, /mask-image|clip-path/, 'hero layers should use masks or clipping to simulate separation');
assert.match(motion, /quickTo/, 'mouse-following motion should use GSAP quickTo');
assert.match(motion, /personMax\s*=\s*12/, 'foreground character mouse parallax should cap at 12px');
assert.match(motion, /shadowMax\s*=\s*5/, 'background shadow mouse parallax should cap at 5px');
assert.match(motion, /typeMax\s*=\s*3/, 'background typography mouse parallax should cap at 3px');
assert.match(motion, /sine\.inOut/, 'idle float should use ease-in-out motion');
assert.match(motion, /duration:\s*5(?:\.|,)|duration:\s*4(?:\.|,)|duration:\s*6(?:\.|,)/, 'idle float should use a 4-6 second cycle');
assert.match(motion, /1\.0(?:2[5-9]|3[0-5])/, 'hover should gently scale the character between 1.025 and 1.035');
assert.doesNotMatch(motion, /scrub/, 'scroll should avoid scrubbed hero parallax to stay smooth');
assert.match(motion, /matchMedia|pointer:\s*fine|hover:\s*hover/, 'mouse following should be disabled on touch/mobile contexts');
assert.doesNotMatch(html + css + motion, /particles\.js|three\.js|pixi/i, 'hero atmosphere should not use a heavy particle library');
assert.match(motion, /ScrollTrigger/, 'motion should use ScrollTrigger');
assert.match(motion, /registerPlugin\(ScrollTrigger\)/, 'ScrollTrigger should be registered');
assert.match(motion, /openingTimeline/, 'opening animation should have its own timeline');
assert.match(motion, /openingTitleDuration\s*=\s*0\.96/, 'YI XUAN opening title entrance should be slightly slower');
assert.match(motion, /playHeroStaggerOpening/, 'YI XUAN completion should trigger the staggered hero opening');
assert.match(motion, /staggerSlices/, 'staggered hero opening should animate sliced curtain panels');
assert.match(motion, /finishHeroOpening/, 'hero ambient interactions should start after the staggered curtain finishes');
assert.match(motion, /releaseHeroOpeningState/, 'hero opening state should be released before the curtain fully disappears');
assert.match(motion, /requestAnimationFrame\(\(\)\s*=>\s*\{[\s\S]*requestAnimationFrame\(\(\)\s*=>\s*ScrollTrigger\.refresh\(\)\)/, 'ScrollTrigger refresh should be deferred to avoid a visible pause after the curtain');
assert.match(motion, /stagger/, 'cards and grouped content should animate with stagger');
assert.match(motion, /power[234]\.out|expo\.out|power[234]\.inOut/, 'motion should use smooth premium easing');
assert.doesNotMatch(motion, /bounce|elastic/, 'motion should not use cheap bounce or elastic easing');
assert.match(motion, /prefers-reduced-motion/, 'motion should respect reduced motion');
